# Author: Dominic
# Github: https://github.com/Dominic-github/
 
# Global
# Check Os
ifdef OS # Windown
	RM = del /Q
	RMDIR = rmdir /q /s
	COPY = copy

else # Linux, Unix, MacOs
	RM = rm -rf
	RMDIR = rm -rf
	COPY =  cp -r

# Get shell
# UNAME_S := $(shell uname -s)
endif
